# flake8: noqa
# fmt: off
from typing import Sequence

__version__ = "0.2.0"

# OK CHANGES

def ok_unchanged(a, *args, b=1, **kwargs): ...
def ok_unchanged_with_hints(a: int, b: float = 5.0) -> bool: ...
def ok_add_optional_param(a, c=2): ...
def ok_change_keywordonly_position(a, *, c=2, b=1): ...
def ok_change_return_type() -> list: ...


# BREAKING CHANGES

def change_param_name(a, c): ...
def remove_param(a): ...
def add_required_param(a, b): ...
def change_kwarg_to_pos(a, b): ...
def change_positional_position(b, a): ...
def change_keyword_position(a, c=2, b=1): ...
def change_param_default(a, b=2): ...
def change_pos_to_keyword_only(a, *, b=1): ...
def change_return_type_incompatible() -> Sequence: ...
def _removed_public_function(): ...

class T:
    ok_stays = 'something'
    changes_type: int = 1
    _private_change = 2

    def ok_meth(self): ...
    def meth_add_required_param(self, a): ...
    @property
    def becomes_property(self): ...
    def no_longer_property(self): ...
    def _ok_change_private_meth(self, a, b): ...


CHANGES_TYPE: int = 1
_PRIVATE_CHANGE = None
