# flake8: noqa
# fmt: off
from typing import Sequence

__version__ = "0.1.0"

# OK CHANGES

def ok_unchanged(a, *args, b=1, **kwargs): ...
def ok_unchanged_with_hints(a: int, b: float = 5.0) -> bool: ...
def ok_add_optional_param(a): ...
def ok_change_keywordonly_position(a, *, b=1, c=2): ...
def ok_change_return_type() -> Sequence: ...
def _ok_removed_private_function(): ...

# BREAKING CHANGES

def change_param_name(a, b): ...
def remove_param(a, b): ...
def add_required_param(a): ...
def change_kwarg_to_pos(a, b=1): ...
def change_positional_position(a, b): ...
def change_keyword_position(a, b=1, c=2): ...
def change_param_default(a, b=1): ...
def change_pos_to_keyword_only(a, b=1): ...
def change_return_type_incompatible() -> list: ...
def removed_public_function(): ...

class T:
    ok_stays = 'something'
    changes_type: str = '1'
    _private_change = 1
    _private_remove = None

    def ok_meth(self): ...
    def meth_add_required_param(self, a): ...
    def becomes_property(self): ...
    @property
    def no_longer_property(self): ...
    def _ok_change_private_meth(self): ...

CHANGES_TYPE: str = '1'
_PRIVATE_CHANGE = 1
_PRIVATE_REMOVE = None
